/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hambuergesas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author madrid
 */
public class MenuHamburguesas extends javax.swing.JFrame implements ActionListener{
    /*
    Creamos nuestos paneles que van a ir cambiando
    */
    protected TipoHamburgesa panelHambur=new TipoHamburgesa();
    protected BebidasExtras panelExtras=new BebidasExtras();
    protected Tipopatatas panelPatata=new Tipopatatas();
    protected Tipopan panelPan=new Tipopan();
    protected PagoCuenta panelCuenta=new PagoCuenta();
    
   
    /*declaramos la clase controlador*/
    Controlador control =new Controlador();


    
    /**
     * Creates new form MenuHamburguesas
     */
    public MenuHamburguesas() {
        initComponents();
        this.setLocationRelativeTo(null);
       base.add(panelHambur);
       panelHambur.setVisible(true);
       panelPatata.setVisible(false);
       panelPan.setVisible(false);
       panelExtras.setVisible(false);
       panelCuenta.setVisible(false);
       
       apagar();
       
       botonInicio.addActionListener(this);
       botonSiguiente.addActionListener(this);
       
       
    }
    /**
     * Activa y desactiva los botones (inicio, siguiente y pago)dependiendo el panel en que este
     */
    private void apagar(){
        if(panelHambur.isVisible()){
            botonInicio.setEnabled(false); //para desabilitar los botones
            botonSiguiente.setEnabled(true);
            botonpagar.setEnabled(false);
        }else if(panelCuenta.isVisible()){
            botonInicio.setEnabled(true); //para desabilitar los botones
            botonSiguiente.setEnabled(false);
            botonpagar.setEnabled(true);
        }else{
            botonInicio.setEnabled(true);
            botonSiguiente.setEnabled(true);
            botonpagar.setEnabled(false);

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        mando = new javax.swing.JPanel();
        botonSiguiente = new javax.swing.JButton();
        botonInicio = new javax.swing.JButton();
        botonpagar = new javax.swing.JButton();
        vistaPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.setLayout(new java.awt.BorderLayout());

        mando.setBackground(new java.awt.Color(0, 0, 0));

        botonSiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");

        botonInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonInicio.setText("Inicio");

        botonpagar.setBackground(new java.awt.Color(0, 0, 0));
        botonpagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonpagar.setForeground(new java.awt.Color(255, 255, 255));
        botonpagar.setText("Pagar");

        vistaPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vistaPrecio.setForeground(new java.awt.Color(255, 255, 255));
        vistaPrecio.setText("0,00€");

        javax.swing.GroupLayout mandoLayout = new javax.swing.GroupLayout(mando);
        mando.setLayout(mandoLayout);
        mandoLayout.setHorizontalGroup(
            mandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mandoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(botonpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vistaPrecio)
                .addGap(37, 37, 37))
        );
        mandoLayout.setVerticalGroup(
            mandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mandoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(mandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonpagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonSiguiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(botonInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mandoLayout.createSequentialGroup()
                        .addComponent(vistaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(mando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHamburguesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHamburguesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHamburguesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHamburguesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHamburguesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton botonpagar;
    private javax.swing.JPanel mando;
    private javax.swing.JLabel vistaPrecio;
    // End of variables declaration//GEN-END:variables
    /**
     * las acciones que hace al presionar cada boton
     * @param e 
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        
        Object evt =e.getSource();
        if(evt.equals(botonInicio)){
            //visualiza el panel haburguesa y los otros los oculta 
            panelHambur.setVisible(true);
            panelPatata.setVisible(false);
            panelPan.setVisible(false);
            panelCuenta.setVisible(false); 
            panelExtras.setVisible(false);
            //Añadimos el panel visible al panel base
            base.add(panelHambur);
            base.validate();
            apagar();
           vistaPrecio.setText(String.valueOf(control.getPrecio()));
           
        }else if(evt.equals(botonSiguiente)&& panelHambur.isVisible()){
            //visualiza el panel pan y los otros los oculta
            panelHambur.setVisible(false);
            panelPatata.setVisible(false);
            panelPan.setVisible(true); 
            panelCuenta.setVisible(false);
            panelExtras.setVisible(false);
            //Añadimos el panel visible al panel base
            base.add(panelPan);
            base.validate();
            //Enviamos el precio de la hamburguesa al panel 
            control.setHamburguesa((panelHambur.getPrecio()));
            apagar();
            panelCuenta.setpHamburguesa(String.valueOf(panelHambur.getPrecio()));
            //que se vizualice en parte inferior el precio actual
            vistaPrecio.setText(String.valueOf(control.getPrecio()));
        }
         else if(evt.equals(botonSiguiente)&& panelPan.isVisible()){
            panelPan.setVisible(false);
            panelPatata.setVisible(true);
            panelHambur.setVisible(false);
            panelCuenta.setVisible(false);
            panelExtras.setVisible(false);
            base.add(panelPatata);            
            base.validate();
            apagar();
        }else if(evt.equals(botonSiguiente)&& panelPatata.isVisible()){
            panelPatata.setVisible(false);
            panelExtras.setVisible(true);
            panelPan.setVisible(false);
            panelHambur.setVisible(false);
            panelCuenta.setVisible(false);
            base.add(panelExtras);
            control.setPatatas((panelPatata.getPrecio()));
            vistaPrecio.setText(String.valueOf(control.getPrecio()));
            panelCuenta.setpPatatas(String.valueOf(panelPatata.getPrecio()));
            base.validate();
            apagar();
        }else if(evt.equals(botonSiguiente)&& panelExtras.isVisible()){
            control.setSalsas(panelExtras.calcularSalsas());          
            panelCuenta.cuentaprecios(control.getPrecio());//enviamos el calculo de los precios para imprimir
            panelCuenta.cuentaprecios(panelExtras.getPrecio());//Envio del descuento 0 no y -1 si
            panelCuenta.setpSalsas(String.valueOf(panelExtras.calcularSalsas()));
            panelPatata.setVisible(false);
            panelPan.setVisible(false);
            panelHambur.setVisible(false);
            panelExtras.setVisible(false);
            panelCuenta.setVisible(true);
            vistaPrecio.setText(panelCuenta.getTotalconIVA());
            base.add(panelCuenta);
            apagar();
        }
    }
}
