/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hambuergesas;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author madrid
 */
public class Tipopatatas extends javax.swing.JPanel {
    protected double precio =0;
    /**
     * Creates new form Tipocarne
     */
    public Tipopatatas() {
        initComponents();
    }
    @Override
    public void paint(Graphics g){
        Dimension dimension=this.getSize();
        ImageIcon icono=new ImageIcon(getClass().getResource("/imagen/fondo2.jpg"));
        g.drawImage(icono.getImage(),0,0,dimension.width, dimension.height,null);//la ubicacion de la imagen en el eje 0x y 0y y el tamaño de ancho y alto
        this.setOpaque(false); //que los otros componentes se sobrepongan a la imagen 
        super.paintChildren(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonFritas = new javax.swing.JButton();
        botonGajos = new javax.swing.JButton();
        botonCaceras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        botonFritas.setBackground(new java.awt.Color(0, 0, 0));
        botonFritas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonFritas.setForeground(new java.awt.Color(255, 255, 255));
        botonFritas.setText("Fritas");
        botonFritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFritasActionPerformed(evt);
            }
        });

        botonGajos.setBackground(new java.awt.Color(0, 0, 0));
        botonGajos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGajos.setForeground(new java.awt.Color(255, 255, 255));
        botonGajos.setText("Gajo");
        botonGajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGajosActionPerformed(evt);
            }
        });

        botonCaceras.setBackground(new java.awt.Color(0, 0, 0));
        botonCaceras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCaceras.setForeground(new java.awt.Color(255, 255, 255));
        botonCaceras.setText("Caceras");
        botonCaceras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCacerasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige tus patatas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGajos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFritas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCaceras, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonFritas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGajos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCaceras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCacerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCacerasActionPerformed
        // TODO add your handling code here:
        botonGajos.setEnabled(false);
        botonFritas.setEnabled(false);
        this.precio=1;
    }//GEN-LAST:event_botonCacerasActionPerformed

    private void botonGajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGajosActionPerformed
        // TODO add your handling code here:
        botonCaceras.setEnabled(false);
        botonFritas.setEnabled(false);
    }//GEN-LAST:event_botonGajosActionPerformed

    private void botonFritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFritasActionPerformed
        // TODO add your handling code here:
        botonGajos.setEnabled(false);
        botonCaceras.setEnabled(false);
    }//GEN-LAST:event_botonFritasActionPerformed

    public double getPrecio() {
        return precio;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCaceras;
    private javax.swing.JButton botonFritas;
    private javax.swing.JButton botonGajos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
