/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hambuergesas;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author madrid
 */
public class Tipopan extends javax.swing.JPanel {
     protected double precio =0;
    /**
     * Creates new form Tipocarne
     */
    public Tipopan() {
        initComponents();
    }
    @Override
    public void paint(Graphics g){
        Dimension dimension=this.getSize();
        ImageIcon icono=new ImageIcon(getClass().getResource("/imagen/fondo2.jpg"));
        g.drawImage(icono.getImage(),0,0,dimension.width, dimension.height,null);//la ubicacion de la imagen en el eje 0x y 0y y el tamaño de ancho y alto
        this.setOpaque(false); //que los otros componentes se sobrepongan a la imagen 
        super.paintChildren(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPnormal = new javax.swing.JButton();
        botonPintegral = new javax.swing.JButton();
        botonCenteno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        botonPnormal.setBackground(new java.awt.Color(0, 0, 0));
        botonPnormal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonPnormal.setForeground(new java.awt.Color(255, 255, 255));
        botonPnormal.setText("Normal");
        botonPnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPnormalActionPerformed(evt);
            }
        });

        botonPintegral.setBackground(new java.awt.Color(0, 0, 0));
        botonPintegral.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonPintegral.setForeground(new java.awt.Color(255, 255, 255));
        botonPintegral.setText("Integral");
        botonPintegral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPintegralActionPerformed(evt);
            }
        });

        botonCenteno.setBackground(new java.awt.Color(0, 0, 0));
        botonCenteno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCenteno.setForeground(new java.awt.Color(255, 255, 255));
        botonCenteno.setText("Centeno");
        botonCenteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCentenoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige tu pan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPintegral, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCenteno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonPnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPintegral, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCenteno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCentenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCentenoActionPerformed
        // TODO add your handling code here:
        botonPintegral.setEnabled(false);
        botonPnormal.setEnabled(false);
    }//GEN-LAST:event_botonCentenoActionPerformed

    private void botonPintegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPintegralActionPerformed
        // TODO add your handling code here:
        botonCenteno.setEnabled(false);
        botonPnormal.setEnabled(false);
    }//GEN-LAST:event_botonPintegralActionPerformed

    private void botonPnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPnormalActionPerformed
        // TODO add your handling code here:
        botonPintegral.setEnabled(false);
        botonCenteno.setEnabled(false);
    }//GEN-LAST:event_botonPnormalActionPerformed

    public double getPrecio() {
        return precio;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCenteno;
    private javax.swing.JButton botonPintegral;
    private javax.swing.JButton botonPnormal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
