/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hambuergesas;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author madrid
 */
public class TipoHamburgesa extends javax.swing.JPanel {

    double precio =0;

    /**
     * Creates new form Tipocarne
     */
    public TipoHamburgesa() {
        initComponents();
    }
    @Override
    public void paint(Graphics g){
        Dimension dimension=this.getSize();
        ImageIcon icono=new ImageIcon(getClass().getResource("/imagen/fondo2.jpg"));
        g.drawImage(icono.getImage(),0,0,dimension.width, dimension.height,null);//la ubicacion de la imagen en el eje 0x y 0y y el tamaño de ancho y alto
        this.setOpaque(false); //que los otros componentes se sobrepongan a la imagen 
        super.paintChildren(g);//
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonpollo = new javax.swing.JButton();
        botoncerdo = new javax.swing.JButton();
        botonternera = new javax.swing.JButton();
        botonvegana = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        botonpollo.setBackground(new java.awt.Color(0, 0, 0));
        botonpollo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonpollo.setForeground(new java.awt.Color(255, 255, 255));
        botonpollo.setText("Pollo");
        botonpollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpolloActionPerformed(evt);
            }
        });

        botoncerdo.setBackground(new java.awt.Color(0, 0, 0));
        botoncerdo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botoncerdo.setForeground(new java.awt.Color(255, 255, 255));
        botoncerdo.setText("Cerdo");
        botoncerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerdoActionPerformed(evt);
            }
        });

        botonternera.setBackground(new java.awt.Color(0, 0, 0));
        botonternera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonternera.setForeground(new java.awt.Color(255, 255, 255));
        botonternera.setText("Ternera +1€");
        botonternera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonterneraActionPerformed(evt);
            }
        });

        botonvegana.setBackground(new java.awt.Color(0, 0, 0));
        botonvegana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonvegana.setForeground(new java.awt.Color(255, 255, 255));
        botonvegana.setText("Vegana +1€");
        botonvegana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonveganaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige tu \nhamburgesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoncerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonpollo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonvegana, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonternera, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonpollo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoncerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonternera, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonvegana, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonveganaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonveganaActionPerformed
        // TODO add your handling code here:  
            botoncerdo.setEnabled(false);
            botonpollo.setEnabled(false);
            botonternera.setEnabled(false);
            precio=9;
    }//GEN-LAST:event_botonveganaActionPerformed

    private void botonterneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonterneraActionPerformed
        // TODO add your handling code here:
            botoncerdo.setEnabled(false);
            botonpollo.setEnabled(false);
            botonvegana.setEnabled(false);
             precio=9;
    }//GEN-LAST:event_botonterneraActionPerformed

    private void botoncerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerdoActionPerformed
        // TODO add your handling code here:
        botonvegana.setEnabled(false);
        botonpollo.setEnabled(false);
        botonternera.setEnabled(false);
         precio=8;
    }//GEN-LAST:event_botoncerdoActionPerformed

    public double getPrecio() {
        return precio;
    }

    private void botonpolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpolloActionPerformed
        // TODO add your handling code here:
        botoncerdo.setEnabled(false);
        botonvegana.setEnabled(false);
        botonternera.setEnabled(false);
        precio=8;
    }//GEN-LAST:event_botonpolloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncerdo;
    private javax.swing.JButton botonpollo;
    private javax.swing.JButton botonternera;
    private javax.swing.JButton botonvegana;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
